apiVersion: v1
kind: Service
metadata:
  name: stellaris-webhook-svc
  namespace: stellaris-system
  labels:
    app: stellaris-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    app: stellaris-webhook