apiVersion: v1
kind: ServiceAccount
metadata:
  name: stellaris-webhook-admission
  namespace: stellaris-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stellaris-webhook-admission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stellaris-webhook-admission
subjects:
  - kind: ServiceAccount
    name: stellaris-webhook-admission
    namespace: stellaris-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: stellaris-webhook-admission
  namespace: stellaris-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stellaris-webhook-admission
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - get
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stellaris-webhook-admission
  namespace: stellaris-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stellaris-webhook-admission
subjects:
  - kind: ServiceAccount
    name: stellaris-webhook-admission
    namespace: stellaris-system

