apiVersion: batch/v1
kind: Job
metadata:
  name: stellaris-webhook-create
  namespace: stellaris-system
  labels:
    app: stellaris-webhook-create
spec:
  template:
    metadata:
      name: stellaris-webhook-create
      labels:
        app: stellaris-webhook-create
    spec:
      containers:
        - name: create-secret
          image: wonderflow/kube-webhook-certgen:v2.1
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=stellaris-webhook-svc,stellaris-webhook-svc.stellaris-system.svc
            - --namespace=stellaris-system
            - --secret-name=stellaris-webhook-cert
            - --key-name=tls.key
            - --cert-name=tls.crt
      restartPolicy: OnFailure
      serviceAccountName: stellaris-webhook-admission
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000