apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webhook-svc
  labels:
    app: {{ .Release.Name }}-core
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: https
  selector:
    app: {{ .Release.Name }}-core-manager