apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Release.Name }}-validating-config
  labels:
    app: {{ .Release.Name }}-validating-config
webhooks:
- name: validating.multicluster.harmonycloud.cn.v1alpha1.clusterresources
  sideEffects: None
  admissionReviewVersions:
  - v1
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["multicluster.harmonycloud.cn"]
    apiVersions: ["v1alpha1"]
    resources: ["clusterresources"]
    scope: "Namespaced"
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: "/validating-v1alpha1-clusterresource"
  failurePolicy: Ignore
  timeoutSeconds: 5
- name: validating.multicluster.harmonycloud.cn.v1alpha1.multiclusterresourceaggregaterules
  sideEffects: None
  admissionReviewVersions:
  - v1
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: [ "multicluster.harmonycloud.cn" ]
    apiVersions: [ "v1alpha1" ]
    resources: [ "multiclusterresourceaggregaterules" ]
    scope: "Namespaced"
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: "/validating-v1alpha1-multiclusterresourceaggregaterules"
  failurePolicy: Ignore
  timeoutSeconds: 5
- name: validating.multicluster.harmonycloud.cn.v1alpha1.multiclusterresource
  sideEffects: None
  admissionReviewVersions:
  - v1
  rules:
  - operations: [ "CREATE", "UPDATE" ]
    apiGroups: [ "multicluster.harmonycloud.cn" ]
    apiVersions: [ "v1alpha1" ]
    resources: [ "multiclusterresources" ]
    scope: "Namespaced"
  clientConfig:
    caBundle: Cg==
    service:
      name: {{ .Release.Name }}-webhook-svc
      namespace: {{ .Release.Namespace }}
      path: "/validating-v1alpha1-multiclusterresource"
  failurePolicy: Ignore
  timeoutSeconds: 5